// This file is automatically generated using import-from-p8.py

const NoteSpec sfx16NotesbumbleBots[32] = {
    NoteSpec { .note=Note::C4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::C4, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::C4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=7, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
};
const TuneSpec sfx16bumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx16NotesbumbleBots
};
const NoteSpec sfx17NotesbumbleBots[32] = {
    NoteSpec { .note=Note::Ds4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Fs4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Fs4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Fs4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
};
const TuneSpec sfx17bumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx17NotesbumbleBots
};
const NoteSpec sfx18NotesbumbleBots[32] = {
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Gs5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx18bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx18NotesbumbleBots
};
const NoteSpec sfx19NotesbumbleBots[32] = {
    NoteSpec { .note=Note::Fs5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx19bumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx19NotesbumbleBots
};
const NoteSpec sfx20NotesbumbleBots[32] = {
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D6, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C6, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx20bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx20NotesbumbleBots
};
const NoteSpec sfx21NotesbumbleBots[32] = {
    NoteSpec { .note=Note::As5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=1, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx21bumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx21NotesbumbleBots
};
const NoteSpec sfx22NotesbumbleBots[32] = {
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Gs4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Gs4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
};
const TuneSpec sfx22bumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx22NotesbumbleBots
};
const NoteSpec sfx23NotesbumbleBots[32] = {
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::B4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::B4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
};
const TuneSpec sfx23bumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx23NotesbumbleBots
};
const NoteSpec sfx24NotesbumbleBots[32] = {
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Gs4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Gs4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
};
const TuneSpec sfx24bumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx24NotesbumbleBots
};
const NoteSpec sfx25NotesbumbleBots[32] = {
    NoteSpec { .note=Note::As4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::B4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::B4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
};
const TuneSpec sfx25bumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx25NotesbumbleBots
};
const NoteSpec sfx26NotesbumbleBots[32] = {
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
};
const TuneSpec sfx26bumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx26NotesbumbleBots
};
const NoteSpec sfx27NotesbumbleBots[32] = {
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::A3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=4, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A3, .vol=5, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx27bumbleBots = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx27NotesbumbleBots
};
const NoteSpec sfx28NotesbumbleBots[32] = {
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx28bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx28NotesbumbleBots
};
const NoteSpec sfx29NotesbumbleBots[32] = {
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G3, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G3, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As3, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As2, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As2, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As2, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As2, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As3, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As3, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx29bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx29NotesbumbleBots
};
const NoteSpec sfx30NotesbumbleBots[32] = {
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds2, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
};
const TuneSpec sfx30bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx30NotesbumbleBots
};
const NoteSpec sfx31NotesbumbleBots[32] = {
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Gs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx31bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx31NotesbumbleBots
};
const NoteSpec sfx32NotesbumbleBots[32] = {
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx32bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx32NotesbumbleBots
};
const NoteSpec sfx33NotesbumbleBots[32] = {
    NoteSpec { .note=Note::Fs2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Cs3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As2, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
};
const TuneSpec sfx33bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx33NotesbumbleBots
};
const NoteSpec sfx34NotesbumbleBots[32] = {
    NoteSpec { .note=Note::A5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::A5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::A5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Gs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Cs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx34bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx34NotesbumbleBots
};
const NoteSpec sfx35NotesbumbleBots[32] = {
    NoteSpec { .note=Note::A4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::A4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::A4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::A4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Cs5, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Cs5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Cs4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Cs4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Cs4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As3, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds3, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx35bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx35NotesbumbleBots
};
const NoteSpec sfx36NotesbumbleBots[32] = {
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::F2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::F2, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    SILENCE,
};
const TuneSpec sfx36bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx36NotesbumbleBots
};
const NoteSpec sfx37NotesbumbleBots[32] = {
    NoteSpec { .note=Note::Ds5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::D5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F4, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::F4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As4, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::F4, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx37bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx37NotesbumbleBots
};
const NoteSpec sfx38NotesbumbleBots[32] = {
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds5, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::F4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::F4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::F4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds5, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds5, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds5, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx38bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx38NotesbumbleBots
};
const NoteSpec sfx39NotesbumbleBots[32] = {
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Gs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Fs5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::B4, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
};
const TuneSpec sfx39bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx39NotesbumbleBots
};
const NoteSpec sfx40NotesbumbleBots[32] = {
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Cs6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    SILENCE,
};
const TuneSpec sfx40bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx40NotesbumbleBots
};
const NoteSpec sfx41NotesbumbleBots[32] = {
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
};
const TuneSpec sfx41bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx41NotesbumbleBots
};
const NoteSpec sfx42NotesbumbleBots[32] = {
    NoteSpec { .note=Note::C4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::D4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::D4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::D4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G3, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::As3, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As3, .vol=4, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As3, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As3, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx42bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 0, .numNotes = 32, .notes = sfx42NotesbumbleBots
};
const NoteSpec sfx43NotesbumbleBots[32] = {
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C3, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C2, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G2, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
};
const TuneSpec sfx43bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx43NotesbumbleBots
};
const NoteSpec sfx44NotesbumbleBots[32] = {
    NoteSpec { .note=Note::Fs4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs4, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::A4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::A4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::A4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::A4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs4, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::A4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::A4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::A4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::A4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
};
const TuneSpec sfx44bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx44NotesbumbleBots
};
const NoteSpec sfx45NotesbumbleBots[32] = {
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::F3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::F3, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::F3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::F3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
};
const TuneSpec sfx45bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx45NotesbumbleBots
};
const NoteSpec sfx46NotesbumbleBots[32] = {
    NoteSpec { .note=Note::C3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C3, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C3, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C2, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    SILENCE,
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds2, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Fs3, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_IN },
};
const TuneSpec sfx46bumbleBots = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx46NotesbumbleBots
};

const TuneSpec *const pattern0TunesbumbleBots[1] = { &sfx16bumbleBots };
const PatternSpec pattern0bumbleBots = PatternSpec {
    .numTunes = 1, .tunes = pattern0TunesbumbleBots
};
const TuneSpec *const pattern1TunesbumbleBots[1] = { &sfx17bumbleBots };
const PatternSpec pattern1bumbleBots = PatternSpec {
    .numTunes = 1, .tunes = pattern1TunesbumbleBots
};
const TuneSpec *const pattern3TunesbumbleBots[2] = { &sfx16bumbleBots, &sfx18bumbleBots };
const PatternSpec pattern3bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern3TunesbumbleBots
};
const TuneSpec *const pattern4TunesbumbleBots[2] = { &sfx17bumbleBots, &sfx19bumbleBots };
const PatternSpec pattern4bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern4TunesbumbleBots
};
const TuneSpec *const pattern5TunesbumbleBots[2] = { &sfx16bumbleBots, &sfx20bumbleBots };
const PatternSpec pattern5bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern5TunesbumbleBots
};
const TuneSpec *const pattern6TunesbumbleBots[2] = { &sfx17bumbleBots, &sfx21bumbleBots };
const PatternSpec pattern6bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern6TunesbumbleBots
};
const TuneSpec *const pattern7TunesbumbleBots[2] = { &sfx16bumbleBots, &sfx22bumbleBots };
const PatternSpec pattern7bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern7TunesbumbleBots
};
const TuneSpec *const pattern8TunesbumbleBots[2] = { &sfx17bumbleBots, &sfx23bumbleBots };
const PatternSpec pattern8bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern8TunesbumbleBots
};
const TuneSpec *const pattern9TunesbumbleBots[2] = { &sfx16bumbleBots, &sfx24bumbleBots };
const PatternSpec pattern9bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern9TunesbumbleBots
};
const TuneSpec *const pattern10TunesbumbleBots[2] = { &sfx17bumbleBots, &sfx25bumbleBots };
const PatternSpec pattern10bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern10TunesbumbleBots
};
const TuneSpec *const pattern11TunesbumbleBots[3] = { &sfx16bumbleBots, &sfx24bumbleBots, &sfx18bumbleBots };
const PatternSpec pattern11bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern11TunesbumbleBots
};
const TuneSpec *const pattern12TunesbumbleBots[3] = { &sfx17bumbleBots, &sfx25bumbleBots, &sfx19bumbleBots };
const PatternSpec pattern12bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern12TunesbumbleBots
};
const TuneSpec *const pattern13TunesbumbleBots[3] = { &sfx16bumbleBots, &sfx24bumbleBots, &sfx20bumbleBots };
const PatternSpec pattern13bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern13TunesbumbleBots
};
const TuneSpec *const pattern14TunesbumbleBots[3] = { &sfx17bumbleBots, &sfx25bumbleBots, &sfx21bumbleBots };
const PatternSpec pattern14bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern14TunesbumbleBots
};
const TuneSpec *const pattern15TunesbumbleBots[3] = { &sfx16bumbleBots, &sfx24bumbleBots, &sfx26bumbleBots };
const PatternSpec pattern15bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern15TunesbumbleBots
};
const TuneSpec *const pattern16TunesbumbleBots[3] = { &sfx17bumbleBots, &sfx25bumbleBots, &sfx26bumbleBots };
const PatternSpec pattern16bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern16TunesbumbleBots
};
const TuneSpec *const pattern17TunesbumbleBots[2] = { &sfx16bumbleBots, &sfx26bumbleBots };
const PatternSpec pattern17bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern17TunesbumbleBots
};
const TuneSpec *const pattern18TunesbumbleBots[2] = { &sfx16bumbleBots, &sfx27bumbleBots };
const PatternSpec pattern18bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern18TunesbumbleBots
};
const TuneSpec *const pattern19TunesbumbleBots[3] = { &sfx16bumbleBots, &sfx18bumbleBots, &sfx26bumbleBots };
const PatternSpec pattern19bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern19TunesbumbleBots
};
const TuneSpec *const pattern20TunesbumbleBots[3] = { &sfx17bumbleBots, &sfx19bumbleBots, &sfx26bumbleBots };
const PatternSpec pattern20bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern20TunesbumbleBots
};
const TuneSpec *const pattern21TunesbumbleBots[3] = { &sfx16bumbleBots, &sfx20bumbleBots, &sfx26bumbleBots };
const PatternSpec pattern21bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern21TunesbumbleBots
};
const TuneSpec *const pattern22TunesbumbleBots[3] = { &sfx17bumbleBots, &sfx21bumbleBots, &sfx26bumbleBots };
const PatternSpec pattern22bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern22TunesbumbleBots
};
const TuneSpec *const pattern23TunesbumbleBots[2] = { &sfx24bumbleBots, &sfx26bumbleBots };
const PatternSpec pattern23bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern23TunesbumbleBots
};
const TuneSpec *const pattern31TunesbumbleBots[2] = { &sfx28bumbleBots, &sfx29bumbleBots };
const PatternSpec pattern31bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern31TunesbumbleBots
};
const TuneSpec *const pattern32TunesbumbleBots[3] = { &sfx30bumbleBots, &sfx28bumbleBots, &sfx29bumbleBots };
const PatternSpec pattern32bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern32TunesbumbleBots
};
const TuneSpec *const pattern33TunesbumbleBots[2] = { &sfx30bumbleBots, &sfx31bumbleBots };
const PatternSpec pattern33bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern33TunesbumbleBots
};
const TuneSpec *const pattern34TunesbumbleBots[2] = { &sfx30bumbleBots, &sfx32bumbleBots };
const PatternSpec pattern34bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern34TunesbumbleBots
};
const TuneSpec *const pattern35TunesbumbleBots[3] = { &sfx30bumbleBots, &sfx31bumbleBots, &sfx29bumbleBots };
const PatternSpec pattern35bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern35TunesbumbleBots
};
const TuneSpec *const pattern36TunesbumbleBots[3] = { &sfx30bumbleBots, &sfx32bumbleBots, &sfx29bumbleBots };
const PatternSpec pattern36bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern36TunesbumbleBots
};
const TuneSpec *const pattern37TunesbumbleBots[3] = { &sfx33bumbleBots, &sfx34bumbleBots, &sfx35bumbleBots };
const PatternSpec pattern37bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern37TunesbumbleBots
};
const TuneSpec *const pattern38TunesbumbleBots[3] = { &sfx36bumbleBots, &sfx37bumbleBots, &sfx38bumbleBots };
const PatternSpec pattern38bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern38TunesbumbleBots
};
const TuneSpec *const pattern39TunesbumbleBots[3] = { &sfx30bumbleBots, &sfx39bumbleBots, &sfx29bumbleBots };
const PatternSpec pattern39bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern39TunesbumbleBots
};
const TuneSpec *const pattern40TunesbumbleBots[3] = { &sfx30bumbleBots, &sfx40bumbleBots, &sfx29bumbleBots };
const PatternSpec pattern40bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern40TunesbumbleBots
};
const TuneSpec *const pattern43TunesbumbleBots[1] = { &sfx30bumbleBots };
const PatternSpec pattern43bumbleBots = PatternSpec {
    .numTunes = 1, .tunes = pattern43TunesbumbleBots
};
const TuneSpec *const pattern44TunesbumbleBots[2] = { &sfx30bumbleBots, &sfx41bumbleBots };
const PatternSpec pattern44bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern44TunesbumbleBots
};
const TuneSpec *const pattern45TunesbumbleBots[3] = { &sfx30bumbleBots, &sfx41bumbleBots, &sfx42bumbleBots };
const PatternSpec pattern45bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern45TunesbumbleBots
};
const TuneSpec *const pattern46TunesbumbleBots[1] = { &sfx43bumbleBots };
const PatternSpec pattern46bumbleBots = PatternSpec {
    .numTunes = 1, .tunes = pattern46TunesbumbleBots
};
const TuneSpec *const pattern49TunesbumbleBots[2] = { &sfx33bumbleBots, &sfx34bumbleBots };
const PatternSpec pattern49bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern49TunesbumbleBots
};
const TuneSpec *const pattern50TunesbumbleBots[2] = { &sfx36bumbleBots, &sfx37bumbleBots };
const PatternSpec pattern50bumbleBots = PatternSpec {
    .numTunes = 2, .tunes = pattern50TunesbumbleBots
};
const TuneSpec *const pattern51TunesbumbleBots[3] = { &sfx30bumbleBots, &sfx41bumbleBots, &sfx39bumbleBots };
const PatternSpec pattern51bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern51TunesbumbleBots
};
const TuneSpec *const pattern52TunesbumbleBots[3] = { &sfx30bumbleBots, &sfx41bumbleBots, &sfx40bumbleBots };
const PatternSpec pattern52bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern52TunesbumbleBots
};
const TuneSpec *const pattern53TunesbumbleBots[3] = { &sfx33bumbleBots, &sfx34bumbleBots, &sfx44bumbleBots };
const PatternSpec pattern53bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern53TunesbumbleBots
};
const TuneSpec *const pattern54TunesbumbleBots[3] = { &sfx36bumbleBots, &sfx37bumbleBots, &sfx45bumbleBots };
const PatternSpec pattern54bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern54TunesbumbleBots
};
const TuneSpec *const pattern55TunesbumbleBots[3] = { &sfx30bumbleBots, &sfx41bumbleBots, &sfx46bumbleBots };
const PatternSpec pattern55bumbleBots = PatternSpec {
    .numTunes = 3, .tunes = pattern55TunesbumbleBots
};

const PatternSpec *const song0PatternsbumbleBots[25] = {
    &pattern0bumbleBots,
    &pattern1bumbleBots,
    &pattern1bumbleBots,
    &pattern3bumbleBots,
    &pattern4bumbleBots,
    &pattern5bumbleBots,
    &pattern6bumbleBots,
    &pattern7bumbleBots,
    &pattern8bumbleBots,
    &pattern9bumbleBots,
    &pattern10bumbleBots,
    &pattern11bumbleBots,
    &pattern12bumbleBots,
    &pattern13bumbleBots,
    &pattern14bumbleBots,
    &pattern15bumbleBots,
    &pattern16bumbleBots,
    &pattern17bumbleBots,
    &pattern18bumbleBots,
    &pattern19bumbleBots,
    &pattern20bumbleBots,
    &pattern21bumbleBots,
    &pattern22bumbleBots,
    &pattern23bumbleBots,
    &pattern23bumbleBots,
};
const SongSpec song0bumbleBots = SongSpec {
    .loopStart = 9, .numPatterns = 25, .patterns = song0PatternsbumbleBots
};
const PatternSpec *const song43PatternsbumbleBots[26] = {
    &pattern43bumbleBots,
    &pattern44bumbleBots,
    &pattern45bumbleBots,
    &pattern46bumbleBots,
    &pattern33bumbleBots,
    &pattern44bumbleBots,
    &pattern49bumbleBots,
    &pattern50bumbleBots,
    &pattern51bumbleBots,
    &pattern52bumbleBots,
    &pattern53bumbleBots,
    &pattern54bumbleBots,
    &pattern55bumbleBots,
    &pattern55bumbleBots,
    &pattern45bumbleBots,
    &pattern46bumbleBots,
    &pattern33bumbleBots,
    &pattern34bumbleBots,
    &pattern35bumbleBots,
    &pattern36bumbleBots,
    &pattern37bumbleBots,
    &pattern38bumbleBots,
    &pattern39bumbleBots,
    &pattern40bumbleBots,
    &pattern37bumbleBots,
    &pattern38bumbleBots,
};
const SongSpec song43bumbleBots = SongSpec {
    .loopStart = 0, .numPatterns = 26, .patterns = song43PatternsbumbleBots
};
