// This file is automatically generated using import-from-p8.py

const NoteSpec sfx10NotesPatShooter[32] = {
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::C2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
};
const TuneSpec sfx10PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx10NotesPatShooter
};
const NoteSpec sfx11NotesPatShooter[32] = {
    NoteSpec { .note=Note::C4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::F4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::G4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::As4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::G4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::F4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
};
const TuneSpec sfx11PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx11NotesPatShooter
};
const NoteSpec sfx12NotesPatShooter[32] = {
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds2, .vol=8, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    SILENCE,
};
const TuneSpec sfx12PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx12NotesPatShooter
};
const NoteSpec sfx13NotesPatShooter[32] = {
    NoteSpec { .note=Note::Ds4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::G4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::As4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C5, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::As4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::G4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::F4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::G4, .vol=8, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    SILENCE,
};
const TuneSpec sfx13PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx13NotesPatShooter
};
const NoteSpec sfx14NotesPatShooter[32] = {
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::D4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
};
const TuneSpec sfx14PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx14NotesPatShooter
};
const NoteSpec sfx15NotesPatShooter[32] = {
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::D4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
};
const TuneSpec sfx15PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx15NotesPatShooter
};
const NoteSpec sfx16NotesPatShooter[32] = {
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Fs4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::E4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
};
const TuneSpec sfx16PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx16NotesPatShooter
};
const NoteSpec sfx17NotesPatShooter[32] = {
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
};
const TuneSpec sfx17PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx17NotesPatShooter
};
const NoteSpec sfx18NotesPatShooter[32] = {
    NoteSpec { .note=Note::C3, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::SAW, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::G6, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::SAW, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::SAW, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::SAW, .fx=Effect::DROP },
    NoteSpec { .note=Note::C3, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::DROP },
    NoteSpec { .note=Note::G6, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::SAW, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C3, .vol=3, .wav=WaveForm::PULSE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::SAW, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::G6, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::SAW, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::SAW, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::G6, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds3, .vol=2, .wav=WaveForm::SAW, .fx=Effect::DROP },
    SILENCE,
};
const TuneSpec sfx18PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx18NotesPatShooter
};
const NoteSpec sfx20NotesPatShooter[32] = {
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::Ds6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::D6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As5, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx20PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx20NotesPatShooter
};
const NoteSpec sfx21NotesPatShooter[32] = {
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::D6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::D6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D6, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx21PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx21NotesPatShooter
};
const NoteSpec sfx22NotesPatShooter[32] = {
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C5, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx22PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx22NotesPatShooter
};
const NoteSpec sfx23NotesPatShooter[32] = {
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As4, .vol=2, .wav=WaveForm::TILTED_SAW, .fx=Effect::VIBRATO },
};
const TuneSpec sfx23PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx23NotesPatShooter
};
const NoteSpec sfx24NotesPatShooter[32] = {
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::F4, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
};
const TuneSpec sfx24PatShooter = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx24NotesPatShooter
};

const TuneSpec* pattern0TunesPatShooter[2] = { &sfx10PatShooter, &sfx11PatShooter };
const PatternSpec pattern0PatShooter = PatternSpec {
    .numTunes = 2, .tunes = pattern0TunesPatShooter
};
const TuneSpec* pattern1TunesPatShooter[2] = { &sfx10PatShooter, &sfx11PatShooter };
const PatternSpec pattern1PatShooter = PatternSpec {
    .numTunes = 2, .tunes = pattern1TunesPatShooter
};
const TuneSpec* pattern2TunesPatShooter[2] = { &sfx12PatShooter, &sfx13PatShooter };
const PatternSpec pattern2PatShooter = PatternSpec {
    .numTunes = 2, .tunes = pattern2TunesPatShooter
};
const TuneSpec* pattern3TunesPatShooter[2] = { &sfx12PatShooter, &sfx13PatShooter };
const PatternSpec pattern3PatShooter = PatternSpec {
    .numTunes = 2, .tunes = pattern3TunesPatShooter
};
const TuneSpec* pattern4TunesPatShooter[3] = { &sfx10PatShooter, &sfx11PatShooter, &sfx14PatShooter };
const PatternSpec pattern4PatShooter = PatternSpec {
    .numTunes = 3, .tunes = pattern4TunesPatShooter
};
const TuneSpec* pattern5TunesPatShooter[3] = { &sfx10PatShooter, &sfx11PatShooter, &sfx15PatShooter };
const PatternSpec pattern5PatShooter = PatternSpec {
    .numTunes = 3, .tunes = pattern5TunesPatShooter
};
const TuneSpec* pattern6TunesPatShooter[3] = { &sfx12PatShooter, &sfx13PatShooter, &sfx16PatShooter };
const PatternSpec pattern6PatShooter = PatternSpec {
    .numTunes = 3, .tunes = pattern6TunesPatShooter
};
const TuneSpec* pattern7TunesPatShooter[3] = { &sfx12PatShooter, &sfx13PatShooter, &sfx17PatShooter };
const PatternSpec pattern7PatShooter = PatternSpec {
    .numTunes = 3, .tunes = pattern7TunesPatShooter
};
const TuneSpec* pattern8TunesPatShooter[2] = { &sfx18PatShooter, &sfx20PatShooter };
const PatternSpec pattern8PatShooter = PatternSpec {
    .numTunes = 2, .tunes = pattern8TunesPatShooter
};
const TuneSpec* pattern9TunesPatShooter[2] = { &sfx18PatShooter, &sfx20PatShooter };
const PatternSpec pattern9PatShooter = PatternSpec {
    .numTunes = 2, .tunes = pattern9TunesPatShooter
};
const TuneSpec* pattern10TunesPatShooter[2] = { &sfx18PatShooter, &sfx21PatShooter };
const PatternSpec pattern10PatShooter = PatternSpec {
    .numTunes = 2, .tunes = pattern10TunesPatShooter
};
const TuneSpec* pattern11TunesPatShooter[2] = { &sfx18PatShooter, &sfx21PatShooter };
const PatternSpec pattern11PatShooter = PatternSpec {
    .numTunes = 2, .tunes = pattern11TunesPatShooter
};
const TuneSpec* pattern12TunesPatShooter[3] = { &sfx18PatShooter, &sfx20PatShooter, &sfx22PatShooter };
const PatternSpec pattern12PatShooter = PatternSpec {
    .numTunes = 3, .tunes = pattern12TunesPatShooter
};
const TuneSpec* pattern13TunesPatShooter[3] = { &sfx18PatShooter, &sfx20PatShooter, &sfx22PatShooter };
const PatternSpec pattern13PatShooter = PatternSpec {
    .numTunes = 3, .tunes = pattern13TunesPatShooter
};
const TuneSpec* pattern14TunesPatShooter[3] = { &sfx18PatShooter, &sfx21PatShooter, &sfx23PatShooter };
const PatternSpec pattern14PatShooter = PatternSpec {
    .numTunes = 3, .tunes = pattern14TunesPatShooter
};
const TuneSpec* pattern15TunesPatShooter[3] = { &sfx18PatShooter, &sfx20PatShooter, &sfx24PatShooter };
const PatternSpec pattern15PatShooter = PatternSpec {
    .numTunes = 3, .tunes = pattern15TunesPatShooter
};

const PatternSpec* song0PatternsPatShooter[8] = {
    &pattern0PatShooter,
    &pattern1PatShooter,
    &pattern2PatShooter,
    &pattern3PatShooter,
    &pattern4PatShooter,
    &pattern5PatShooter,
    &pattern6PatShooter,
    &pattern7PatShooter,
};
const SongSpec song0PatShooter = SongSpec {
    .loopStart = 0, .numPatterns = 8, .patterns = song0PatternsPatShooter
};
const PatternSpec* song8PatternsPatShooter[8] = {
    &pattern8PatShooter,
    &pattern9PatShooter,
    &pattern10PatShooter,
    &pattern11PatShooter,
    &pattern12PatShooter,
    &pattern13PatShooter,
    &pattern14PatShooter,
    &pattern15PatShooter,
};
const SongSpec song8PatShooter = SongSpec {
    .loopStart = 0, .numPatterns = 8, .patterns = song8PatternsPatShooter
};
