// WARNING: First sound effect in pattern 0 loops
// WARNING: First sound effect in pattern 1 loops
// WARNING: First sound effect in pattern 2 loops
// WARNING: First sound effect in pattern 3 loops
// WARNING: First sound effect in pattern 4 loops
// WARNING: First sound effect in pattern 5 loops
// WARNING: First sound effect in pattern 6 loops
// WARNING: First sound effect in pattern 7 loops
// WARNING: All sound effects in pattern 8 loop!
// WARNING: All sound effects in pattern 9 loop!
// WARNING: All sound effects in pattern 10 loop!
// WARNING: All sound effects in pattern 11 loop!
// WARNING: The available volume range is not fully used: max = 4 < 7
// This file is automatically generated using import-from-p8.py

const NoteSpec sfx8NotesZepton[32] = {
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx8Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 32, .numNotes = 32, .notes = sfx8NotesZepton
};
const NoteSpec sfx9NotesZepton[32] = {
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=3, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx9Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 32, .numNotes = 32, .notes = sfx9NotesZepton
};
const NoteSpec sfx10NotesZepton[32] = {
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=3, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx10Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 32, .numNotes = 32, .notes = sfx10NotesZepton
};
const NoteSpec sfx11NotesZepton[32] = {
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=3, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx11Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 32, .numNotes = 32, .notes = sfx11NotesZepton
};
const NoteSpec sfx12NotesZepton[32] = {
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=5, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=5, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=5, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=5, .vol=5, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx12Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 32, .numNotes = 32, .notes = sfx12NotesZepton
};
const NoteSpec sfx14NotesZepton[32] = {
    NoteSpec { .note=Note::C, .oct=3, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=3, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=7, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=6, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::Ds, .oct=4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=3, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=4, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=7, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=5, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C, .oct=2, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C, .oct=3, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=3, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=7, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=5, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C, .oct=4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C, .oct=3, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=3, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=7, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=5, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_IN },
    NoteSpec { .note=Note::C, .oct=2, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    SILENCE,
};
const TuneSpec sfx14Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 32, .notes = sfx14NotesZepton
};
const NoteSpec sfx16NotesZepton[16] = {
    NoteSpec { .note=Note::C, .oct=4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds, .oct=4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds, .oct=4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=5, .vol=4, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=3, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=5, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=5, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=3, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=5, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=4, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx16Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 16, .notes = sfx16NotesZepton
};
const NoteSpec sfx18NotesZepton[16] = {
    NoteSpec { .note=Note::D, .oct=4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=5, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A, .oct=4, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=5, .vol=4, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A, .oct=4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=5, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=5, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A, .oct=4, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=5, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=5, .vol=4, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A, .oct=4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx18Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 16, .notes = sfx18NotesZepton
};
const NoteSpec sfx19NotesZepton[16] = {
    NoteSpec { .note=Note::C, .oct=4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=5, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=5, .vol=4, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=5, .vol=2, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=5, .vol=4, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=4, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=5, .vol=2, .wav=WaveForm::SQUARE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=5, .vol=4, .wav=WaveForm::PULSE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=2, .wav=WaveForm::SAW, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx19Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 16, .notes = sfx19NotesZepton
};
const NoteSpec sfx20NotesZepton[8] = {
    NoteSpec { .note=Note::D, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx20Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 8, .notes = sfx20NotesZepton
};
const NoteSpec sfx21NotesZepton[8] = {
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx21Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 8, .notes = sfx21NotesZepton
};
const NoteSpec sfx22NotesZepton[8] = {
    NoteSpec { .note=Note::D, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A, .oct=3, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx22Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 8, .notes = sfx22NotesZepton
};
const NoteSpec sfx23NotesZepton[8] = {
    NoteSpec { .note=Note::C, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=3, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=3, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx23Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 8, .notes = sfx23NotesZepton
};
const NoteSpec sfx24NotesZepton[8] = {
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::As, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx24Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 8, .notes = sfx24NotesZepton
};
const NoteSpec sfx25NotesZepton[8] = {
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::Gs, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx25Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 8, .notes = sfx25NotesZepton
};
const NoteSpec sfx26NotesZepton[32] = {
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx26Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 32, .numNotes = 32, .notes = sfx26NotesZepton
};
const NoteSpec sfx27NotesZepton[8] = {
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx27Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 8, .notes = sfx27NotesZepton
};
const NoteSpec sfx28NotesZepton[8] = {
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx28Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 8, .notes = sfx28NotesZepton
};
const NoteSpec sfx30NotesZepton[8] = {
    NoteSpec { .note=Note::F, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::D, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A, .oct=3, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::F, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::A, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx30Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 8, .notes = sfx30NotesZepton
};
const NoteSpec sfx31NotesZepton[8] = {
    NoteSpec { .note=Note::E, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=3, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::E, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::G, .oct=4, .vol=2, .wav=WaveForm::PHASER, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx31Zepton = TuneSpec {
    .noteDuration = 12, .loopStart = 0, .numNotes = 8, .notes = sfx31NotesZepton
};

const TuneSpec* pattern0TunesZepton[4] = { &sfx16Zepton, &sfx8Zepton, &sfx14Zepton, &sfx28Zepton };
const PatternSpec pattern0Zepton = PatternSpec {
    .numTunes = 4, .tunes = pattern0TunesZepton
};
const TuneSpec* pattern1TunesZepton[4] = { &sfx16Zepton, &sfx9Zepton, &sfx14Zepton, &sfx24Zepton };
const PatternSpec pattern1Zepton = PatternSpec {
    .numTunes = 4, .tunes = pattern1TunesZepton
};
const TuneSpec* pattern2TunesZepton[4] = { &sfx16Zepton, &sfx10Zepton, &sfx14Zepton, &sfx25Zepton };
const PatternSpec pattern2Zepton = PatternSpec {
    .numTunes = 4, .tunes = pattern2TunesZepton
};
const TuneSpec* pattern3TunesZepton[4] = { &sfx16Zepton, &sfx11Zepton, &sfx14Zepton, &sfx26Zepton };
const PatternSpec pattern3Zepton = PatternSpec {
    .numTunes = 4, .tunes = pattern3TunesZepton
};
const TuneSpec* pattern4TunesZepton[4] = { &sfx16Zepton, &sfx10Zepton, &sfx14Zepton, &sfx25Zepton };
const PatternSpec pattern4Zepton = PatternSpec {
    .numTunes = 4, .tunes = pattern4TunesZepton
};
const TuneSpec* pattern5TunesZepton[4] = { &sfx16Zepton, &sfx9Zepton, &sfx14Zepton, &sfx24Zepton };
const PatternSpec pattern5Zepton = PatternSpec {
    .numTunes = 4, .tunes = pattern5TunesZepton
};
const TuneSpec* pattern6TunesZepton[4] = { &sfx16Zepton, &sfx12Zepton, &sfx14Zepton, &sfx27Zepton };
const PatternSpec pattern6Zepton = PatternSpec {
    .numTunes = 4, .tunes = pattern6TunesZepton
};
const TuneSpec* pattern7TunesZepton[4] = { &sfx16Zepton, &sfx8Zepton, &sfx14Zepton, &sfx28Zepton };
const PatternSpec pattern7Zepton = PatternSpec {
    .numTunes = 4, .tunes = pattern7TunesZepton
};
const TuneSpec* pattern8TunesZepton[4] = { &sfx18Zepton, &sfx20Zepton, &sfx22Zepton, &sfx30Zepton };
const PatternSpec pattern8Zepton = PatternSpec {
    .numTunes = 4, .tunes = pattern8TunesZepton
};
const TuneSpec* pattern9TunesZepton[4] = { &sfx18Zepton, &sfx20Zepton, &sfx22Zepton, &sfx30Zepton };
const PatternSpec pattern9Zepton = PatternSpec {
    .numTunes = 4, .tunes = pattern9TunesZepton
};
const TuneSpec* pattern10TunesZepton[4] = { &sfx19Zepton, &sfx21Zepton, &sfx23Zepton, &sfx31Zepton };
const PatternSpec pattern10Zepton = PatternSpec {
    .numTunes = 4, .tunes = pattern10TunesZepton
};
const TuneSpec* pattern11TunesZepton[4] = { &sfx19Zepton, &sfx21Zepton, &sfx23Zepton, &sfx31Zepton };
const PatternSpec pattern11Zepton = PatternSpec {
    .numTunes = 4, .tunes = pattern11TunesZepton
};

const PatternSpec* song0PatternsZepton[8] = {
    &pattern0Zepton,
    &pattern1Zepton,
    &pattern2Zepton,
    &pattern3Zepton,
    &pattern4Zepton,
    &pattern5Zepton,
    &pattern6Zepton,
    &pattern7Zepton,
};
const SongSpec song0Zepton = SongSpec {
    .loopStart = 0, .numPatterns = 8, .patterns = song0PatternsZepton
};
const PatternSpec* song8PatternsZepton[4] = {
    &pattern8Zepton,
    &pattern9Zepton,
    &pattern10Zepton,
    &pattern11Zepton,
};
const SongSpec song8Zepton = SongSpec {
    .loopStart = 0, .numPatterns = 4, .patterns = song8PatternsZepton
};
