// This file is automatically generated using import-from-p8.py

const NoteSpec sfx16Notes[32] = {
    NoteSpec { .note=Note::C, .oct=4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::Ds, .oct=4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=4, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::Ds, .oct=4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=4, .vol=6, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=4, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=4, .vol=7, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
    NoteSpec { .note=Note::Ds, .oct=4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::NONE },
    SILENCE,
};
const TuneSpec sfx16 = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx16Notes
};
const NoteSpec sfx17Notes[32] = {
    NoteSpec { .note=Note::Ds, .oct=4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=4, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Fs, .oct=4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds, .oct=4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=4, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Fs, .oct=4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Ds, .oct=4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=4, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=4, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Ds, .oct=4, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=3, .vol=7, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=4, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=4, .vol=5, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
    NoteSpec { .note=Note::Fs, .oct=4, .vol=3, .wav=WaveForm::ORGAN, .fx=Effect::VIBRATO },
    SILENCE,
};
const TuneSpec sfx17 = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx17Notes
};
const NoteSpec sfx18Notes[32] = {
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Gs, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx18 = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx18Notes
};
const NoteSpec sfx19Notes[32] = {
    NoteSpec { .note=Note::Fs, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx19 = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx19Notes
};
const NoteSpec sfx20Notes[32] = {
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::D, .oct=6, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=6, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::C, .oct=6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::C, .oct=6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G, .oct=5, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::G, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::G, .oct=5, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::VIBRATO },
    NoteSpec { .note=Note::As, .oct=6, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=6, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx20 = TuneSpec {
    .noteDuration = 32, .loopStart = 32, .numNotes = 32, .notes = sfx20Notes
};
const NoteSpec sfx21Notes[32] = {
    NoteSpec { .note=Note::As, .oct=6, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=6, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=4, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=3, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::SLIDE },
    NoteSpec { .note=Note::As, .oct=6, .vol=2, .wav=WaveForm::TRIANGLE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
    SILENCE,
};
const TuneSpec sfx21 = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx21Notes
};
const NoteSpec sfx22Notes[32] = {
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Ds, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::G, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Gs, .oct=4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Ds, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::G, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Gs, .oct=4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
};
const TuneSpec sfx22 = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx22Notes
};
const NoteSpec sfx23Notes[32] = {
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Fs, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::As, .oct=6, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::B, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::Fs, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=4, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    SILENCE,
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::As, .oct=6, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::B, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=5, .vol=4, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
};
const TuneSpec sfx23 = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx23Notes
};
const NoteSpec sfx24Notes[32] = {
    NoteSpec { .note=Note::G, .oct=4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Gs, .oct=4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=3, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::D, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::C, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Gs, .oct=4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::G, .oct=4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
};
const TuneSpec sfx24 = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx24Notes
};
const NoteSpec sfx25Notes[32] = {
    NoteSpec { .note=Note::As, .oct=5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=6, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::B, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=4, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=4, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=3, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=6, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Fs, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::F, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::Ds, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::B, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
    NoteSpec { .note=Note::As, .oct=5, .vol=5, .wav=WaveForm::TILTED_SAW, .fx=Effect::NONE },
};
const TuneSpec sfx25 = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx25Notes
};
const NoteSpec sfx26Notes[32] = {
    NoteSpec { .note=Note::C, .oct=3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=4, .vol=6, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C, .oct=3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=4, .vol=6, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C, .oct=3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=4, .vol=6, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C, .oct=3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=4, .vol=6, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C, .oct=3, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
};
const TuneSpec sfx26 = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx26Notes
};
const NoteSpec sfx27Notes[32] = {
    NoteSpec { .note=Note::C, .oct=3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C, .oct=4, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=6, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=4, .vol=6, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=2, .vol=5, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    NoteSpec { .note=Note::C, .oct=3, .vol=8, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C, .oct=4, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=6, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    SILENCE,
    NoteSpec { .note=Note::C, .oct=3, .vol=6, .wav=WaveForm::TRIANGLE, .fx=Effect::DROP },
    SILENCE,
    NoteSpec { .note=Note::C, .oct=4, .vol=2, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=3, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=4, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
    NoteSpec { .note=Note::C, .oct=4, .vol=6, .wav=WaveForm::NOISE, .fx=Effect::FADE_OUT },
};
const TuneSpec sfx27 = TuneSpec {
    .noteDuration = 16, .loopStart = 32, .numNotes = 32, .notes = sfx27Notes
};

const TuneSpec* pattern0Tunes[1] = { &sfx16 };
const PatternSpec pattern0 = PatternSpec {
    .numTunes = 1, .tunes = pattern0Tunes
};
const TuneSpec* pattern1Tunes[1] = { &sfx17 };
const PatternSpec pattern1 = PatternSpec {
    .numTunes = 1, .tunes = pattern1Tunes
};
const TuneSpec* pattern2Tunes[1] = { &sfx17 };
const PatternSpec pattern2 = PatternSpec {
    .numTunes = 1, .tunes = pattern2Tunes
};
const TuneSpec* pattern3Tunes[2] = { &sfx16, &sfx18 };
const PatternSpec pattern3 = PatternSpec {
    .numTunes = 2, .tunes = pattern3Tunes
};
const TuneSpec* pattern4Tunes[2] = { &sfx17, &sfx19 };
const PatternSpec pattern4 = PatternSpec {
    .numTunes = 2, .tunes = pattern4Tunes
};
const TuneSpec* pattern5Tunes[2] = { &sfx16, &sfx20 };
const PatternSpec pattern5 = PatternSpec {
    .numTunes = 2, .tunes = pattern5Tunes
};
const TuneSpec* pattern6Tunes[2] = { &sfx17, &sfx21 };
const PatternSpec pattern6 = PatternSpec {
    .numTunes = 2, .tunes = pattern6Tunes
};
const TuneSpec* pattern7Tunes[2] = { &sfx16, &sfx22 };
const PatternSpec pattern7 = PatternSpec {
    .numTunes = 2, .tunes = pattern7Tunes
};
const TuneSpec* pattern8Tunes[2] = { &sfx17, &sfx23 };
const PatternSpec pattern8 = PatternSpec {
    .numTunes = 2, .tunes = pattern8Tunes
};
const TuneSpec* pattern9Tunes[2] = { &sfx16, &sfx24 };
const PatternSpec pattern9 = PatternSpec {
    .numTunes = 2, .tunes = pattern9Tunes
};
const TuneSpec* pattern10Tunes[2] = { &sfx17, &sfx25 };
const PatternSpec pattern10 = PatternSpec {
    .numTunes = 2, .tunes = pattern10Tunes
};
const TuneSpec* pattern11Tunes[3] = { &sfx16, &sfx24, &sfx18 };
const PatternSpec pattern11 = PatternSpec {
    .numTunes = 3, .tunes = pattern11Tunes
};
const TuneSpec* pattern12Tunes[3] = { &sfx17, &sfx25, &sfx19 };
const PatternSpec pattern12 = PatternSpec {
    .numTunes = 3, .tunes = pattern12Tunes
};
const TuneSpec* pattern13Tunes[3] = { &sfx16, &sfx24, &sfx20 };
const PatternSpec pattern13 = PatternSpec {
    .numTunes = 3, .tunes = pattern13Tunes
};
const TuneSpec* pattern14Tunes[3] = { &sfx17, &sfx25, &sfx21 };
const PatternSpec pattern14 = PatternSpec {
    .numTunes = 3, .tunes = pattern14Tunes
};
const TuneSpec* pattern15Tunes[3] = { &sfx16, &sfx24, &sfx26 };
const PatternSpec pattern15 = PatternSpec {
    .numTunes = 3, .tunes = pattern15Tunes
};
const TuneSpec* pattern16Tunes[3] = { &sfx17, &sfx25, &sfx26 };
const PatternSpec pattern16 = PatternSpec {
    .numTunes = 3, .tunes = pattern16Tunes
};
const TuneSpec* pattern17Tunes[2] = { &sfx16, &sfx26 };
const PatternSpec pattern17 = PatternSpec {
    .numTunes = 2, .tunes = pattern17Tunes
};
const TuneSpec* pattern18Tunes[2] = { &sfx16, &sfx27 };
const PatternSpec pattern18 = PatternSpec {
    .numTunes = 2, .tunes = pattern18Tunes
};
const TuneSpec* pattern19Tunes[3] = { &sfx16, &sfx18, &sfx26 };
const PatternSpec pattern19 = PatternSpec {
    .numTunes = 3, .tunes = pattern19Tunes
};
const TuneSpec* pattern20Tunes[3] = { &sfx17, &sfx19, &sfx26 };
const PatternSpec pattern20 = PatternSpec {
    .numTunes = 3, .tunes = pattern20Tunes
};
const TuneSpec* pattern21Tunes[3] = { &sfx16, &sfx20, &sfx26 };
const PatternSpec pattern21 = PatternSpec {
    .numTunes = 3, .tunes = pattern21Tunes
};
const TuneSpec* pattern22Tunes[3] = { &sfx17, &sfx21, &sfx26 };
const PatternSpec pattern22 = PatternSpec {
    .numTunes = 3, .tunes = pattern22Tunes
};
const TuneSpec* pattern23Tunes[2] = { &sfx24, &sfx26 };
const PatternSpec pattern23 = PatternSpec {
    .numTunes = 2, .tunes = pattern23Tunes
};
const TuneSpec* pattern24Tunes[2] = { &sfx24, &sfx26 };
const PatternSpec pattern24 = PatternSpec {
    .numTunes = 2, .tunes = pattern24Tunes
};
const TuneSpec* pattern25Tunes[1] = { &sfx17 };
const PatternSpec pattern25 = PatternSpec {
    .numTunes = 1, .tunes = pattern25Tunes
};
const TuneSpec* pattern26Tunes[1] = { &sfx17 };
const PatternSpec pattern26 = PatternSpec {
    .numTunes = 1, .tunes = pattern26Tunes
};
const TuneSpec* pattern27Tunes[2] = { &sfx16, &sfx18 };
const PatternSpec pattern27 = PatternSpec {
    .numTunes = 2, .tunes = pattern27Tunes
};
const TuneSpec* pattern28Tunes[2] = { &sfx17, &sfx19 };
const PatternSpec pattern28 = PatternSpec {
    .numTunes = 2, .tunes = pattern28Tunes
};
const TuneSpec* pattern29Tunes[2] = { &sfx16, &sfx20 };
const PatternSpec pattern29 = PatternSpec {
    .numTunes = 2, .tunes = pattern29Tunes
};
const TuneSpec* pattern30Tunes[2] = { &sfx17, &sfx21 };
const PatternSpec pattern30 = PatternSpec {
    .numTunes = 2, .tunes = pattern30Tunes
};
